version: '2'

services:

  solr_internal:
    image: solr:7.4.0
    restart: always
    volumes:
      - ./solr-internal:/opt/solr/server/solr
    ports:
      - 8983:8983

  solr:
    image: solr:7.4.0
    restart: always
    volumes:
      - ./solr:/opt/solr/server/solr
    ports:
      - 8995:8983

  compile:
    build:
      context: .
      dockerfile: Dockerfile-compile
    volumes:
      - .:/project
